<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EnrollmentMigrationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R00487924',
            'branch_code' => 032,
            'loyalty_number' => 'LP08023808',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);

        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior1@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01855098',
            'branch_code' => 033,
            'loyalty_number' => 'LP08026048',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior2@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R00862795',
            'branch_code' => 022,
            'loyalty_number' => 'LP08026078',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior3@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R07810224',
            'branch_code' => 066,
            'loyalty_number' => 'LP08026090',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior4@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R05263192',
            'branch_code' => 055,
            'loyalty_number' => 'LP08026091',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior5@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04094207',
            'branch_code' => 042,
            'loyalty_number' => 'LP08026102',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior6@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R00515049',
            'branch_code' => 030,
            'loyalty_number' => 'LP08026107',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior7@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04196801',
            'branch_code' => 064,
            'loyalty_number' => 'LP08026111',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior8@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03645830',
            'branch_code' => 044,
            'loyalty_number' => 'LP08026123',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior9@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03132868',
            'branch_code' => 012,
            'loyalty_number' => 'LP08026146',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior10@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R05700673',
            'branch_code' => 035,
            'loyalty_number' => 'LP08026151',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior11@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04550247',
            'branch_code' => 062,
            'loyalty_number' => 'LP08026152',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior12@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06788655',
            'branch_code' => 056,
            'loyalty_number' => 'LP08027229',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior13@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03241255',
            'branch_code' => 037,
            'loyalty_number' => 'LP08029091',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior14@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R07799511',
            'branch_code' => 001,
            'loyalty_number' => 'LP08033223',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior15@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03659837',
            'branch_code' => 002,
            'loyalty_number' => 'LP08033849',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior16@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R07827812',
            'branch_code' => 004,
            'loyalty_number' => 'LP08033916',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior17@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R07827812',
            'branch_code' => 023,
            'loyalty_number' => 'LP08036165',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior18@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02135419',
            'branch_code' => 003,
            'loyalty_number' => 'LP08036514',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior19@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R05151603',
            'branch_code' => 024,
            'loyalty_number' => 'LP08037909',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior20@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06468706',
            'branch_code' => 021,
            'loyalty_number' => 'LP08038692',
            'phone_number' =>  now(),
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior21@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06114418',
            'branch_code' => 011,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08038764',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior22@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06747309',
            'branch_code' => 027,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08038993',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior23@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02730089',
            'branch_code' => 033,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08040502',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior24@mail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02781117',
            'branch_code' => 025,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08040572',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior25@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02781117',
            'branch_code' => 031,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08041589',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior26@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06747113',
            'branch_code' => 002,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08041731',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior27@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02863228',
            'branch_code' => 032,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08043073',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior28@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01466266',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08052814',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior29@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02287819',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08053135',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior30@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03089205',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08054395',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior31@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01629718',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08062733',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior32@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06677715',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08064903',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior33@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03486378',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08083035',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior34@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03712408',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08083875',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior342@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06511383',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08084873',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior35@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06729244',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08085238',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior36@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R05136637',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08086809',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior37@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R07190909',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08095322',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior38@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R07260010',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08011572',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior39@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04523183',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08012008',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior40@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02249231',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08012211',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior41@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02739683',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08012809',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior42@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02739683',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08012956',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior44@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04836220',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08013035',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior45@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06454985',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08013122',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior46@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R07659456',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08013214',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior47@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03639455',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08013305',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior48@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02782659',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08013593',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior49@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03371646',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08014163',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior50@mail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02316602',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08014300',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior51@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04053209',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08014827',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior52@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03051419',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08014885',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior53@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04598928',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08014993',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior54@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01824054',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08015085',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior55@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02821241',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08015262',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior56@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04945494',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08015371',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior57@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04945494',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08015764',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior58@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R05782304',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08016819',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior59@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03271439',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08017087',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior60@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R07262110',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08017199',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior61@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R07262110',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08017409',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior62@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02807792',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08017632',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior63@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R00840057',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08017790',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior64@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03066400',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08017823',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior65@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R05072579',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08017873',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior66@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02758495',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08018104',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior67@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03350837',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08018438',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior68@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R05249419',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08019178',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior69@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02649391',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08019533',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior70@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06923842',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08020776',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior71@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04602947',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08021417',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior72@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06438565',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08022380',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior73@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06455140',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08022762',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior74@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01694511',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08022949',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior75@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R00579125',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08023072',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior76@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06850978',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08023136',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior77@mail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03702657',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08023641',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior78@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01936809',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08023862',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior79@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03586714',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08024312',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior80@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R00330820',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08024403',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior81@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03378542',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08024468',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior82@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02956960',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08024682',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior83@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04094207',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08024819',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior84@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01112212',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08024931',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior85@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01354441',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08025262',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior86@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06290386',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08025318',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior87@@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02473064',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08025775',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior88@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01484025',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08025850',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior89@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03189096',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08025865',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior90@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R03837921',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08025944',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior91@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02429804',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08026478',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior92@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02137909',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08026656',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior93@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R04887697',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08026817',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior94@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01404007',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08027664',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior95@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R05066729',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08028130',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior96@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02145136',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08028367',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior97@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R06668118',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08028687',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior98@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R02708429',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08028871',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
        DB::table('enrollments')->insert([
            'first_name' => 'Jibbs',
            'last_name' => 'Junior',
            'email' => 'jibbsjunior99@gmail.com',
            'enrollment_status' => 0,
            'tries' => 1,
            'member_cif' => 'R01615991',
            'branch_code' => 037,
            'phone_number' =>  now(),
            'loyalty_number' => 'LP08030492',
            'pin' => '0000',
            'password' => 'password',
            'loyalty_program_id' => 1,
            'tier_id' => 1,
            'cron_id' => 1,
        ]);
    }
}
